model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo

  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
      rpm: 5

  - model_name: gemini/gemini-1.0-pro
    litellm_params:
      model: gemini/gemini-1.0-pro
      api_key: "os.environ/GEMINI_API_KEY"

  - model_name: bedrock/anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

general_settings:
  master_key: "os.environ/LITELLM_MASTER_KEY"
