model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo

  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"

  - model_name: nim/mixtral-8x7b-instruct-v0.1
    litellm_params:
      model: openai/mistralai/mixtral-8x7b-instruct-v0.1 # prefix compatible's model with openai/
      api_base: https://integrate.api.nvidia.com/v1
      api_key: "os.environ/NVIDIA_API_KEY"

  - model_name: gemini/gemini-1.0-pro
    litellm_params:
      model: gemini/gemini-1.0-pro
      api_key: "os.environ/GEMINI_API_KEY"

litellm_settings:
  set_verbose: True
  cache: True
  num_retries: 3
  request_timeout: 10
  allowed_fails: 3
